# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpLaOitwNAJ9qVrX_LdkFCb5qOjcj0NT
"""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, Model
import tensorflow.keras.backend as K


print("🔍 Auto-detecting dataset structure...")

DRIVE_PATH = "/content/drive/MyDrive/Colab Notebooks/Deep Learning/Project"
IMAGE_BASE_DIR = os.path.join(DRIVE_PATH, "Image")
MASK_BASE_DIR = os.path.join(DRIVE_PATH, "Masked")

# Check directories exist
if not os.path.exists(IMAGE_BASE_DIR):
    raise FileNotFoundError(f"Image directory not found: {IMAGE_BASE_DIR}")
if not os.path.exists(MASK_BASE_DIR):
    raise FileNotFoundError(f"Mask directory not found: {MASK_BASE_DIR}")

# List subfolders
image_folders = sorted([f for f in os.listdir(IMAGE_BASE_DIR)
                       if os.path.isdir(os.path.join(IMAGE_BASE_DIR, f))])
mask_folders = sorted([f for f in os.listdir(MASK_BASE_DIR)
                      if os.path.isdir(os.path.join(MASK_BASE_DIR, f))])

print(f"Image folders: {image_folders}")
print(f"Mask folders: {mask_folders}")

# Find common folders
common_folders = sorted(set(image_folders) & set(mask_folders))
if not common_folders:
    raise ValueError("No matching folders found between Origin and Mask!")

CLASSES = common_folders
NUM_CLASSES = len(CLASSES) + 1  # +1 for background
print(f"\n Defect classes: {CLASSES}")
print(f"Total classes (with background): {NUM_CLASSES}")

#  LOAD DATA

print("\n Loading dataset with multi-class segmentation mapping...")

def load_multi_class_data():
    """Load data with proper multi-class segmentation mapping"""
    all_images = []
    all_masks = []

    # Create class mapping: folder name -> class index
    class_to_idx = {cls: i+1 for i, cls in enumerate(CLASSES)}

    for class_name in CLASSES:
        img_dir = os.path.join(IMAGE_BASE_DIR, class_name)
        mask_dir = os.path.join(MASK_BASE_DIR, class_name)

        class_idx = class_to_idx[class_name]

        # Get all image files
        for img_file in os.listdir(img_dir):
            if not img_file.lower().endswith(('.png', '.jpg', '.jpeg')):
                continue

            img_path = os.path.join(img_dir, img_file)

            # Try to find corresponding mask
            mask_path = os.path.join(mask_dir, img_file)
            if not os.path.exists(mask_path):
                # Try different extensions
                base_name = os.path.splitext(img_file)[0]
                for ext in ['.png', '.jpg', '.jpeg', '.PNG', '.JPG', '.JPEG']:
                    alt_path = os.path.join(mask_dir, base_name + ext)
                    if os.path.exists(alt_path):
                        mask_path = alt_path
                        break

            if not os.path.exists(mask_path):
                continue

            all_images.append(img_path)
            all_masks.append((mask_path, class_idx))

    print(f"Total image-mask pairs: {len(all_images)}")

    # Analyze defect sizes
    print("\n Defect size analysis:")
    for class_idx, class_name in enumerate(CLASSES, 1):
        class_masks = [m for m in all_masks if m[1] == class_idx]
        if class_masks:
            defect_sizes = []
            for mask_path, _ in class_masks[:10]:  # Sample 10 masks
                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                if mask is not None:
                    defect_pixels = np.sum(mask > 127)
                    total_pixels = mask.shape[0] * mask.shape[1]
                    defect_sizes.append(defect_pixels / total_pixels * 100)

            if defect_sizes:
                avg_size = np.mean(defect_sizes)
                min_size = np.min(defect_sizes)
                max_size = np.max(defect_sizes)
                print(f"  {class_name}: avg {avg_size:.4f}%, range {min_size:.4f}%-{max_size:.4f}%")

    return all_images, all_masks, class_to_idx

all_images, all_masks, class_to_idx = load_multi_class_data()

# TRAIN-VAL SPLIT

# Extract just the image paths and mask paths for splitting
image_paths = all_images
mask_info = all_masks  # (mask_path, class_idx)

train_images, val_images, train_masks, val_masks = train_test_split(
    image_paths, mask_info, test_size=0.2, random_state=42, shuffle=True
)

print(f"\n Dataset split:")
print(f"  Training samples: {len(train_images)}")
print(f"  Validation samples: {len(val_images)}")

class MultiClassSegmentationGenerator(tf.keras.utils.Sequence):
    def __init__(self, *args, **kwargs):
        # Add defect-focused sampling
        self.defect_focus_prob = 0.7  # 70% chance to sample defect-containing images
        super().__init__(*args, **kwargs)

    def on_epoch_end(self):
        # FOCUS ON DEFECT-CONTAINING IMAGES
        self.balanced_indices = []

        # Get indices of images WITH defects (class_idx > 0)
        defect_indices = []
        for class_idx in range(1, self.num_classes):  # Skip background
            defect_indices.extend(self.class_indices[class_idx])

        # Remove duplicates
        defect_indices = list(set(defect_indices))

        # If we have defect images, oversample them
        if defect_indices:
            # Calculate how many defect samples to include (70% of batch)
            n_defect_samples = int(len(defect_indices) * 0.7)
            if n_defect_samples > len(defect_indices):
                # Repeat if needed
                repeats = n_defect_samples // len(defect_indices) + 1
                sampled_defects = defect_indices * repeats
                sampled_defects = sampled_defects[:n_defect_samples]
            else:
                sampled_defects = np.random.choice(defect_indices,
                                                  n_defect_samples,
                                                  replace=False)

            # Add background images for remaining 30%
            background_needed = self.batch_size - len(sampled_defects)
            all_indices = list(range(len(self.image_paths)))
            background_indices = np.random.choice(all_indices,
                                                 background_needed,
                                                 replace=True)

            self.balanced_indices = list(sampled_defects) + list(background_indices)
        else:
            # Fallback to all images
            self.balanced_indices = list(range(len(self.image_paths)))

        if self.shuffle:
            np.random.shuffle(self.balanced_indices)

        self.balanced_indices = np.array(self.balanced_indices)

    def apply_augmentation(self, image, mask):
        """ENHANCED AUGMENTATION FOR TINY DEFECTS"""
        # Store defect location before augmentation
        defect_pixels = np.sum(mask > 127)

        # Random flip
        if np.random.random() > 0.5:
            image = np.fliplr(image)
            mask = np.fliplr(mask)

        # Random rotation - SMALL angles to preserve defect integrity
        if np.random.random() > 0.5:
            angle = np.random.uniform(-15, 15)  # Small rotations
            h, w = image.shape[:2]
            center = (w//2, h//2)

            # Rotate image
            M = cv2.getRotationMatrix2D(center, angle, 1.0)
            image = cv2.warpAffine(image, M, (w, h),
                                  flags=cv2.INTER_LINEAR,
                                  borderMode=cv2.BORDER_REFLECT)

            # Rotate mask with NEAREST interpolation
            mask = cv2.warpAffine(mask, M, (w, h),
                                 flags=cv2.INTER_NEAREST,
                                 borderMode=cv2.BORDER_CONSTANT,
                                 borderValue=0)

        # DEFECT-SPECIFIC AUGMENTATIONS:
        # 1. CLAHE for local contrast enhancement
        if np.random.random() > 0.5 and defect_pixels > 0:
            # Apply CLAHE only around defect region
            lab = cv2.cvtColor(image, cv2.COLOR_RGB2LAB)
            l, a, b = cv2.split(lab)
            clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
            l = clahe.apply(l)
            lab = cv2.merge([l, a, b])
            image = cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)

        # 2. Selective sharpening to enhance defect edges
        if np.random.random() > 0.5 and defect_pixels > 0:
            kernel = np.array([[-1,-1,-1],
                              [-1, 9,-1],
                              [-1,-1,-1]])
            image = cv2.filter2D(image, -1, kernel)

        # 3. Random zoom/crop to make defects larger in context
        if np.random.random() > 0.3 and defect_pixels > 0:
            # Find defect bounding box
            coords = np.column_stack(np.where(mask > 127))
            if len(coords) > 0:
                y1, x1 = coords.min(axis=0)
                y2, x2 = coords.max(axis=0)

                # Zoom in around defect (crop and resize)
                zoom_factor = np.random.uniform(1.5, 2.5)
                h, w = image.shape[:2]

                # Calculate crop around defect
                defect_center = ((y1+y2)//2, (x1+x2)//2)
                crop_size = min(h, w) // 2  # Crop half the image size

                y_start = max(0, defect_center[0] - crop_size//2)
                y_end = min(h, defect_center[0] + crop_size//2)
                x_start = max(0, defect_center[1] - crop_size//2)
                x_end = min(w, defect_center[1] + crop_size//2)

                # Crop and resize back
                if y_end > y_start and x_end > x_start:
                    image_crop = image[y_start:y_end, x_start:x_end]
                    mask_crop = mask[y_start:y_end, x_start:x_end]

                    image = cv2.resize(image_crop, (w, h),
                                     interpolation=cv2.INTER_LINEAR)
                    mask = cv2.resize(mask_crop, (w, h),
                                    interpolation=cv2.INTER_NEAREST)

        # 4. Noise addition ONLY to background (simulate realistic conditions)
        if np.random.random() > 0.7:
            # Add slight noise to entire image
            noise = np.random.randn(*image.shape) * 10
            image = np.clip(image + noise, 0, 255)

        return image, mask

#  CREATE GENERATORS

INPUT_SIZE = 256
BATCH_SIZE = 4
EPOCHS = 20

print(f"\n Creating BALANCED data generators...")

train_gen = MultiClassSegmentationGenerator(
    train_images, train_masks,
    batch_size=BATCH_SIZE,
    input_size=INPUT_SIZE,
    num_classes=NUM_CLASSES,
    shuffle=True,
    augment=True
)

val_gen = MultiClassSegmentationGenerator(
    val_images, val_masks,
    batch_size=BATCH_SIZE,
    input_size=INPUT_SIZE,
    num_classes=NUM_CLASSES,
    shuffle=False,
    augment=False
)

# Check the new balance
sample_images, sample_masks = train_gen[0]
print(f" Balanced generator created!")
print(f"  Batch shape: {sample_images.shape}")
print(f"  Defect pixels in batch: {np.sum(sample_masks[:, :, :, 1:]):,}")
print(f"  Background pixels in batch: {np.sum(sample_masks[:, :, :, 0]):,}")
print(f"  Defect percentage in batch: {(np.sum(sample_masks[:, :, :, 1:]) / sample_masks.size * 100):.2f}%")

# BUILD U-NET FOR MULTI-CLASS SEGMENTATION

def build_multi_class_unet(input_size=256, num_classes=7):
    """Build U-Net for multi-class semantic segmentation"""
    inputs = layers.Input(shape=(input_size, input_size, 3))

    # Encoder
    c1 = layers.Conv2D(64, 3, padding='same', activation='relu')(inputs)
    c1 = layers.Conv2D(64, 3, padding='same', activation='relu')(c1)
    p1 = layers.MaxPooling2D((2, 2))(c1)

    c2 = layers.Conv2D(128, 3, padding='same', activation='relu')(p1)
    c2 = layers.Conv2D(128, 3, padding='same', activation='relu')(c2)
    p2 = layers.MaxPooling2D((2, 2))(c2)

    c3 = layers.Conv2D(256, 3, padding='same', activation='relu')(p2)
    c3 = layers.Conv2D(256, 3, padding='same', activation='relu')(c3)
    p3 = layers.MaxPooling2D((2, 2))(c3)

    c4 = layers.Conv2D(512, 3, padding='same', activation='relu')(p3)
    c4 = layers.Conv2D(512, 3, padding='same', activation='relu')(c4)
    p4 = layers.MaxPooling2D((2, 2))(c4)

    # Bottleneck
    c5 = layers.Conv2D(1024, 3, padding='same', activation='relu')(p4)
    c5 = layers.Conv2D(1024, 3, padding='same', activation='relu')(c5)
    c5 = layers.Dropout(0.5)(c5)

    # Decoder
    u6 = layers.Conv2DTranspose(512, 2, strides=2, padding='same')(c5)
    u6 = layers.concatenate([u6, c4])
    c6 = layers.Conv2D(512, 3, padding='same', activation='relu')(u6)
    c6 = layers.Conv2D(512, 3, padding='same', activation='relu')(c6)

    u7 = layers.Conv2DTranspose(256, 2, strides=2, padding='same')(c6)
    u7 = layers.concatenate([u7, c3])
    c7 = layers.Conv2D(256, 3, padding='same', activation='relu')(u7)
    c7 = layers.Conv2D(256, 3, padding='same', activation='relu')(c7)

    u8 = layers.Conv2DTranspose(128, 2, strides=2, padding='same')(c7)
    u8 = layers.concatenate([u8, c2])
    c8 = layers.Conv2D(128, 3, padding='same', activation='relu')(u8)
    c8 = layers.Conv2D(128, 3, padding='same', activation='relu')(c8)

    u9 = layers.Conv2DTranspose(64, 2, strides=2, padding='same')(c8)
    u9 = layers.concatenate([u9, c1])
    c9 = layers.Conv2D(64, 3, padding='same', activation='relu')(u9)
    c9 = layers.Conv2D(64, 3, padding='same', activation='relu')(c9)

    # Output layer for multi-class segmentation (softmax for single class per pixel)
    outputs = layers.Conv2D(num_classes, 1, activation='softmax')(c9)

    model = Model(inputs=inputs, outputs=outputs, name='MultiClass_UNet')
    return model

print("\n Building U-Net for multi-class segmentation...")
model = build_multi_class_unet(input_size=INPUT_SIZE, num_classes=NUM_CLASSES)
model.summary()

#  LOSS FUNCTIONS FOR MULTI-CLASS SEGMENTATION

def calculate_class_weights_for_loss():
    """Calculate weights: background=1, defects=high weight"""
    # Based on your 99.96% background, 0.04% defects ratio
    background_weight = 1.0

    # Defects need MUCH higher weight to counter imbalance
    # If defects are 0.04% of pixels, weight should be ~2500x
    # But we'll cap at 200 to avoid numerical instability
    defect_weight = 200.0  # Increased from 100 to 200

    class_weights = [background_weight] + [defect_weight] * len(CLASSES)

    print(f"\n Class weights for loss function:")
    print(f"  Background: {background_weight}")
    for i, cls in enumerate(CLASSES):
        print(f"  {cls}: {defect_weight}")

    return class_weights

# Calculate class weights BEFORE defining loss functions
CLASS_WEIGHTS = calculate_class_weights_for_loss()

def weighted_categorical_crossentropy(weights):
    """Custom loss with class weights - MORE AGGRESSIVE"""
    weights_tensor = tf.constant(weights, dtype=tf.float32)

    def loss(y_true, y_pred):
        # Clip predictions to avoid log(0)
        y_pred = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)

        # Calculate weighted categorical crossentropy
        # More weight on defect pixels
        loss_per_pixel = -tf.reduce_sum(y_true * tf.math.log(y_pred) * weights_tensor, axis=-1)

        # Return mean loss
        return tf.reduce_mean(loss_per_pixel)

    return loss

def dice_loss_multi_class(y_true, y_pred, smooth=1e-6):
    """Dice loss for multi-class segmentation - BETTER FOR IMBALANCE"""
    # Flatten
    y_true_f = tf.reshape(y_true, [-1, NUM_CLASSES])
    y_pred_f = tf.reshape(y_pred, [-1, NUM_CLASSES])

    # Calculate intersection and union
    intersection = tf.reduce_sum(y_true_f * y_pred_f, axis=0)
    total = tf.reduce_sum(y_true_f, axis=0) + tf.reduce_sum(y_pred_f, axis=0)

    # Dice coefficient per class
    dice_per_class = (2. * intersection + smooth) / (total + smooth)

    # Focus more on defect classes by weighting
    defect_weight = 2.0  # Give defects 2x more importance in Dice
    class_weights_dice = tf.constant([1.0] + [defect_weight] * len(CLASSES), dtype=tf.float32)

    weighted_dice = dice_per_class * class_weights_dice
    mean_dice = tf.reduce_mean(weighted_dice)

    return 1.0 - mean_dice

def combined_weighted_loss(y_true, y_pred):
    """Combine weighted CE and Dice loss - OPTIMIZED FOR DEFECTS"""
    # Weighted categorical crossentropy (heavily weights defects)
    wce_loss = weighted_categorical_crossentropy(CLASS_WEIGHTS)(y_true, y_pred)

    # Dice loss (good for segmentation boundaries)
    dice_loss_val = dice_loss_multi_class(y_true, y_pred)

    # Use more CE (70%) to focus on class imbalance, less Dice (30%)
    return 0.7 * wce_loss + 0.3 * dice_loss_val

def mean_iou_multi_class(y_true, y_pred):
    """Mean IoU for multi-class segmentation"""
    # Threshold predictions
    y_pred = tf.argmax(y_pred, axis=-1)
    y_pred = tf.one_hot(tf.cast(y_pred, tf.int32), NUM_CLASSES)

    # Calculate intersection and union for each class
    intersection = tf.reduce_sum(y_true * y_pred, axis=[1, 2])
    union = tf.reduce_sum(y_true, axis=[1, 2]) + tf.reduce_sum(y_pred, axis=[1, 2]) - intersection

    # Calculate IoU and average
    iou_per_class = (intersection + 1e-7) / (union + 1e-7)
    return tf.reduce_mean(iou_per_class)

def categorical_accuracy_multi_class(y_true, y_pred):
    """Categorical accuracy for segmentation"""
    # Convert predictions to class indices
    y_pred = tf.argmax(y_pred, axis=-1)
    y_true = tf.argmax(y_true, axis=-1)

    # Calculate accuracy
    equal = tf.cast(tf.equal(y_pred, y_true), tf.float32)
    return tf.reduce_mean(equal)

def defect_only_iou(y_true, y_pred):
    """IoU for DEFECT CLASSES ONLY (excludes background)"""
    # Threshold predictions
    y_pred = tf.argmax(y_pred, axis=-1)
    y_pred = tf.one_hot(tf.cast(y_pred, tf.int32), NUM_CLASSES)

    # Focus only on defect classes (skip background class 0)
    y_true_defects = y_true[..., 1:]
    y_pred_defects = y_pred[..., 1:]

    # Calculate intersection and union for defect classes
    intersection = tf.reduce_sum(y_true_defects * y_pred_defects, axis=[1, 2])
    union = tf.reduce_sum(y_true_defects, axis=[1, 2]) + tf.reduce_sum(y_pred_defects, axis=[1, 2]) - intersection

    # Calculate IoU for defect classes
    iou_defects = tf.where(union > 0, intersection / union, tf.zeros_like(intersection))
    return tf.reduce_mean(iou_defects)

# COMPILE MODEL WITH DEFECT-FOCUSED LOSS

print("\n Compiling model with DEFECT-FOCUSED loss functions...")

# Use a HIGHER learning rate to encourage learning of rare defect patterns
initial_lr = 2e-3  # Increased from 1e-3

lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=initial_lr,
    decay_steps=800,  # More frequent decay
    decay_rate=0.9,   # Faster decay
    staircase=True
)

# Use Adam optimizer with gradient clipping to handle high weights
optimizer = tf.keras.optimizers.Adam(
    learning_rate=lr_schedule,
    clipnorm=1.0  # Clip gradients to prevent explosion from high weights
)

model.compile(
    optimizer=optimizer,
    loss=combined_weighted_loss,  # Our defect-focused loss
    metrics=[
        categorical_accuracy_multi_class,  # Overall accuracy
        mean_iou_multi_class,              # Overall IoU
        defect_only_iou,                   # CRITICAL: Defect-only IoU
        'categorical_accuracy'             # Built-in accuracy
    ]
)

print(" Model compiled with:")
print(f"  - Initial LR: {initial_lr}")
print(f"  - Class weights: Background=1, Defects={CLASS_WEIGHTS[1]}")
print(f"  - Loss: 70% Weighted CE + 30% Dice")
print(f"  - Metrics: Accuracy, Mean IoU, DEFECT-ONLY IoU")

#  CALLBACKS

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        'best_multi_class_segmentation.weights.h5',
        monitor='val_mean_iou_multi_class',
        mode='max',
        save_best_only=True,
        save_weights_only=True,
        verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor='val_mean_iou_multi_class',
        patience=20,
        mode='max',
        restore_best_weights=True,
        verbose=1
    ),
]

#  TRAIN MODEL

print("\n Starting multi-class segmentation training...")
print("=" * 60)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=30,
    callbacks=callbacks,
    verbose=1
)

# FINAL EVALUATION

print("\n Final Evaluation...")
model.load_weights('best_multi_class_segmentation.weights.h5')
val_results = model.evaluate(val_gen, verbose=1)

print(f"\n Final Multi-Class Segmentation Results:")
print(f"  Loss: {val_results[0]:.4f}")
print(f"  Accuracy: {val_results[1]:.4f}")
print(f"  Mean IoU: {val_results[2]:.4f}")

#  COMPREHENSIVE FINAL VISUALIZATION

def plot_final_training_history(history):
    """Create final comprehensive training plots"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    epochs = range(1, len(history.history['loss']) + 1)

    # Plot 1: Loss
    axes[0, 0].plot(epochs, history.history['loss'], 'b-', linewidth=2, label='Training')
    axes[0, 0].plot(epochs, history.history['val_loss'], 'r-', linewidth=2, label='Validation')
    axes[0, 0].set_title('Training and Validation Loss', fontsize=14, fontweight='bold')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # Plot 2: Accuracy
    axes[0, 1].plot(epochs, history.history['categorical_accuracy_multi_class'], 'b-', linewidth=2)
    axes[0, 1].plot(epochs, history.history['val_categorical_accuracy_multi_class'], 'r-', linewidth=2)
    axes[0, 1].set_title('Training and Validation Accuracy', fontsize=14, fontweight='bold')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Accuracy')
    axes[0, 1].legend(['Training', 'Validation'])
    axes[0, 1].grid(True, alpha=0.3)

    # Plot 3: Mean IoU
    axes[0, 2].plot(epochs, history.history['mean_iou_multi_class'], 'b-', linewidth=2)
    axes[0, 2].plot(epochs, history.history['val_mean_iou_multi_class'], 'r-', linewidth=2)
    axes[0, 2].set_title('Training and Validation Mean IoU', fontsize=14, fontweight='bold')
    axes[0, 2].set_xlabel('Epoch')
    axes[0, 2].set_ylabel('IoU')
    axes[0, 2].legend(['Training', 'Validation'])
    axes[0, 2].grid(True, alpha=0.3)

    # Plot 4: Loss vs Accuracy
    axes[1, 0].scatter(history.history['loss'], history.history['categorical_accuracy_multi_class'],
                      alpha=0.5, label='Training', s=20)
    axes[1, 0].scatter(history.history['val_loss'], history.history['val_categorical_accuracy_multi_class'],
                      alpha=0.5, label='Validation', s=20)
    axes[1, 0].set_title('Loss vs Accuracy', fontsize=14, fontweight='bold')
    axes[1, 0].set_xlabel('Loss')
    axes[1, 0].set_ylabel('Accuracy')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # Plot 5: Accuracy vs IoU
    axes[1, 1].scatter(history.history['categorical_accuracy_multi_class'],
                      history.history['mean_iou_multi_class'], alpha=0.5, label='Training', s=20)
    axes[1, 1].scatter(history.history['val_categorical_accuracy_multi_class'],
                      history.history['val_mean_iou_multi_class'], alpha=0.5, label='Validation', s=20)
    axes[1, 1].set_title('Accuracy vs Mean IoU', fontsize=14, fontweight='bold')
    axes[1, 1].set_xlabel('Accuracy')
    axes[1, 1].set_ylabel('IoU')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    # Plot 6: Convergence Analysis
    convergence = []
    for i in range(1, len(epochs)):
        loss_change = abs(history.history['loss'][i] - history.history['loss'][i-1])
        convergence.append(loss_change)

    axes[1, 2].plot(range(2, len(epochs)+1), convergence, 'g-', linewidth=2)
    axes[1, 2].axhline(y=np.mean(convergence[-5:]) if len(convergence) >= 5 else 0,
                      color='r', linestyle='--', label='Avg recent change')
    axes[1, 2].set_title('Loss Convergence', fontsize=14, fontweight='bold')
    axes[1, 2].set_xlabel('Epoch')
    axes[1, 2].set_ylabel('Loss Change')
    axes[1, 2].legend()
    axes[1, 2].grid(True, alpha=0.3)

    plt.suptitle('PCB Multi-Class Defect Segmentation - Complete Training Analysis',
                fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

    # Print training statistics
    print("\n Training Statistics:")
    print("-" * 40)
    print(f"Final Epoch: {len(epochs)}")
    print(f"Best Validation IoU: {max(history.history['val_mean_iou_multi_class']):.4f}")
    print(f"Best Validation Accuracy: {max(history.history['val_categorical_accuracy_multi_class']):.4f}")
    print(f"Training/Validation Gap (IoU): {history.history['mean_iou_multi_class'][-1] - history.history['val_mean_iou_multi_class'][-1]:.4f}")

print("\n Generating final training analysis...")
plot_final_training_history(history)